version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: integration-testing
    ports:
      - 3307:3306
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
